### ISSUE TITLE
Bug: Travis CI build fails with wrong icon size

### ISSUE THREAD

**Issue by JohannBlake** [electron/apps#833]
Attempting to have my app published to Electron's app store is still failing.

After making your bugfix today, a new exception is generated. It indicates something wrong with the icon dimensions. I have in fact verified both files and compared them to other apps. They are RGB, png and use the same naming convention. Here's the log output:

```
> electron-apps@1.4726.0 test /home/travis/build/electron/apps
> mocha --reporter min test/human-data.js test/colors-spec.js && standard --fix

calculating good colors for white
calculating good colors for white
calculating good colors for black
calculating good colors for white
calculating good colors for black
calculating good colors for white
calculating good colors for black
calculating good colors for white
calculating good colors for black
calculating good colors for black
calculating good colors for white
calculating good colors for black
calculating good colors for white
calculating good colors for black
calculating good colors for white

  13167 passing (3s)
  1 failing

  1) human-submitted app data skutti icon is at least 256px x 256px (or 128px x 128px for grandfathered apps):
     AssertionError: expected 144 to be at least 256
      at Context.<anonymous> (test/human-data.js:149:45)
```

**Comment by ckerr** [comment]
> After making your bugfix today,

I'm not sure what this refers to. I did change the merge message of the PR so that the semantic commit bot would be satisfied, but didn't change the contents of your PR.

>  a new exception is generated. It indicates something wrong with the icon dimensions. I have in fact verified both files and compared them to other apps. They are RGB, png and use the same naming convention.

Your icons do follow the same naming convention as other apps, but differs in that `skutti-icon.png` is fewer than 256 x 256 pixels, which is what is causing this test to fail.

If you could provide a larger icon, that would be great.

In the interim, it was my mistake to merge a PR with a failing test so I've created https://github.com/electron/apps/pull/836 to address that.
